name: free_mobile
version: 7.2.0

description: Send SMS messages to your Free Mobile device. A simple and free way to monitor your applications using a Free Mobile account.
homepage: https://dev.belin.io/free-mobile.dart
issue_tracker: https://github.com/cedx/free-mobile.dart/issues
repository: https://github.com/cedx/free-mobile.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies:
  build_runner: ^1.7.3
  build_test: ^0.10.12
  grinder: ^0.8.3
  grinder_coveralls: ^2.1.0
  test: ^1.12.0
